# Generated by Django 3.2.6 on 2021-10-14 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=150)),
                ('thumbnail_image', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('banner_image', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('featured', models.BooleanField(default=True)),
                ('about', models.CharField(blank=True, max_length=10000, null=True)),
                ('Deployed_to', models.CharField(default='DigitalOcean', max_length=20)),
                ('server', models.CharField(default='Ubuntu version 18', max_length=20)),
                ('static_files_handling', models.CharField(max_length=50)),
                ('Database', models.CharField(max_length=30)),
                ('Version_control', models.CharField(max_length=30)),
                ('Authentication_type', models.CharField(max_length=100)),
                ('Backend_framwork', models.CharField(max_length=30)),
                ('Port_routing', models.CharField(max_length=30)),
                ('Frontend_framwork', models.CharField(max_length=30)),
                ('icon_source', models.CharField(max_length=30)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
