# Generated by Django 3.2.6 on 2021-10-19 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20211019_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='about',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
