# Generated by Django 3.2.6 on 2021-10-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Backend_framwork',
            field=models.CharField(blank=True, default='Django', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='Backend_framwork_icon',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='Deployed_to_icon',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='Port_routing_icon',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='Version_control',
            field=models.CharField(default='Git', max_length=30),
        ),
        migrations.AlterField(
            model_name='project',
            name='database_icon',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='server_icon',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='staticfiles_handling_icon',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='version_control_icon',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
