# Generated by Django 3.2.6 on 2021-11-03 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20211103_1112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='backend_framwork',
            new_name='backend_framework',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='backend_framwork_icon',
            new_name='backend_framework_icon',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='frontend_framwork',
            new_name='frontend_framework',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='frontend_framwork_icon',
            new_name='frontend_framework_icon',
        ),
    ]
