# Generated by Django 3.2.6 on 2021-11-05 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='project_title',
            field=models.CharField(blank=True, default='Unspecified', max_length=500, null=True),
        ),
    ]
